# Generated by Django 5.2.8 on 2026-02-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_2fa_enabled',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='totp_secret',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='salt',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
