# Generated by Django 5.2.8 on 2026-02-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_is_2fa_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='recovery_code_hashes',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
