# Generated by Django 5.1.3 on 2026-02-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_userprofile_dek_auth_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='encrypted_private_key',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='private_key_iv',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='private_key_tag',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='public_key',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
