# Generated by Django 5.1.3 on 2026-02-21 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedfile',
            name='encrypted_file_key',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encryptedfile',
            name='file_key_iv',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encryptedfile',
            name='file_key_tag',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FileShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrapped_key', models.BinaryField()),
                ('ephemeral_public', models.BinaryField()),
                ('wrapped_iv', models.BinaryField()),
                ('wrapped_tag', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='drive.encryptedfile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_files', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('file', 'shared_with')},
            },
        ),
    ]
